### ISSUE TITLE
Please make one for ETL!!!

### ISSUE THREAD

**Issue by zeronone** [kuna/snucseAlarm#1]
ETL Support.
I think the difficult part will be SNU Login, right?

**Comment by kuna** [comment]
Hi Arif, long time no see :)
That's a good suggestion, but yes, It's not easy to do with that. I tried it today, but login process is consisted with multiple page access(It seems), so more studying seems to be necessary.
Currently I'll do ETL support later because we can get some new ETL posts by forwarding snu email, and I have difficulty with snu login process. I'd be welcome if you do pull request with this part ;D

**Comment by kuna** [comment]
I think I found the way to obtain SNU session. ETL will be supported soon :)

**Comment by zeronone** [comment]
Wow!! That is great!. I looked at it, but it was giving errors. But I couldn't find much time to debug it :+1:

**Comment by kuna** [comment]
Implementation finished, close issue
